[FIX]

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -32,6 +32,20 @@ jobs:
             echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
             exit 1
             fi
+      - name: file.pain_choco
+        run: |
+          FILE2=$(find . -name "pain_auchocolat")
+            if [[ -n "$FILE2" ]]; then
+            echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
+            exit 1
+            fi
+      - name: file.o
+        run: |
+          FILE2=$(find . -name *.o)
+            if [[ -n "$FILE2" ]]; then
+            echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
+            exit 1
+            fi
       - uses: pixta-dev/repository-mirroring-action@v1
         with:
           target_repo_url:
