[FIX]

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -20,11 +20,18 @@ jobs:
           fetch-death: 0
       - name: file.#
         run: |
-        FILE2=$(find . -name *.#)
-          if [[ -n "$FILE2" ]]; then
-          echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
-          exit 1
-          fi
+          FILE2=$(find . -name *.#)
+            if [[ -n "$FILE2" ]]; then
+            echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
+            exit 1
+            fi
+      - name: file.~
+        run: |
+          FILE2=$(find . -name *.~)
+            if [[ -n "$FILE2" ]]; then
+            echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
+            exit 1
+            fi
       - uses: pixta-dev/repository-mirroring-action@v1
         with:
           target_repo_url:
