[FIX]

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -34,7 +34,7 @@ jobs:
             fi
       - name: file.pain_choco
         run: |
-          FILE2=$(find . -name "pain_auchocolat")
+          FILE2=$(find . -name "pain_au_chocolat")
             if [[ -n "$FILE2" ]]; then
             echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
             exit 1
@@ -42,6 +42,41 @@ jobs:
       - name: file.o
         run: |
           FILE2=$(find . -name *.o)
+            if [[ -n "$FILE2" ]]; then
+            echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
+            exit 1
+            fi
+      - name: file.a
+        run: |
+          FILE2=$(find . -name *.a)
+            if [[ -n "$FILE2" ]]; then
+            echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
+            exit 1
+            fi
+      - name: file.so
+        run: |
+          FILE2=$(find . -name *.so)
+            if [[ -n "$FILE2" ]]; then
+            echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
+            exit 1
+            fi
+      - name: file.gcno
+        run: |
+          FILE2=$(find . -name *.gcno)
+            if [[ -n "$FILE2" ]]; then
+            echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
+            exit 1
+            fi
+      - name: file.gcda
+        run: |
+          FILE2=$(find . -name *.gcda)
+            if [[ -n "$FILE2" ]]; then
+            echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
+            exit 1
+            fi
+      - name: file.gcov
+        run: |
+          FILE2=$(find . -name *.gcov)
             if [[ -n "$FILE2" ]]; then
             echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
             exit 1
