[TEST2]

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,3 +1,4 @@
+
 name: chocolatine
 on: 
   push:
@@ -7,9 +8,9 @@ on:
     branches-ignore:
       - 'ga-ignore-'
 
-env:
-  MIRROR_URL: git@github.com:EpitechPromo2026/B-DOP-200-PAR-2-1-chocolatine-alfred.ternynck.git
-  EXECUTABLES: a.out
+env :
+  MIRROR_URL: git@github.com:EpitechPromo2027/B-DOP-200-PAR-2-1-chocolatine-alfred.ternynck.git
+  executable_name: ./a.out
 
 jobs:
   clean:
@@ -77,6 +78,20 @@ jobs:
       - name: file.gcov
         run: |
           FILE2=$(find . -name *.gcov)
+            if [[ -n "$FILE2" ]]; then
+            echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
+            exit 1
+            fi
+      - name: file.gch
+        run: |
+          FILE2=$(find . -name *.gch)
+            if [[ -n "$FILE2" ]]; then
+            echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
+            exit 1
+            fi
+      - name: file.gcovr
+        run: |
+          FILE2=$(find . -name *.gcovr)
             if [[ -n "$FILE2" ]]; then
             echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
             exit 1
